name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy with pm2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            rm -rf /var/www/apis-docs
            git clone --depth 1 git@github.com:codante-io/apis-docs.git /var/www/apis-docs

            cd /var/www/codante-changelog
            pnpm install
            pnpm run build
            pm2 restart codante-changelog
